spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/composite_pk
    username: postgres
    password: adminroot
  # ensure ddl-auto is validate/false & generate-ddl: false
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
